### ISSUE TITLE
Offer to help

### ISSUE THREAD

**Issue by benwa** [mRemoteNG/mRemoteNG.github.io#1]
I've made a simple site mockup [here](https://github.com/benwa/mRemoteNG/tree/gh-pages).  If you're interested, I can submit a pull request and help work on the site.
![screen shot 2016-08-19 at 21 32 01](https://cloud.githubusercontent.com/assets/1351571/17827962/7804a3c4-6654-11e6-855f-9911bb158ffa.png)
![screen shot 2016-08-19 at 21 32 05](https://cloud.githubusercontent.com/assets/1351571/17827964/78097c50-6654-11e6-8daf-6cb89655912e.png)
![screen shot 2016-08-19 at 21 32 09](https://cloud.githubusercontent.com/assets/1351571/17827963/7809103a-6654-11e6-9e93-0a587973fd1e.png)
![screen shot 2016-08-19 at 21 32 14](https://cloud.githubusercontent.com/assets/1351571/17827965/780a24c0-6654-11e6-9bbe-908796162696.png)
![screen shot 2016-08-20 at 11 27 28](https://cloud.githubusercontent.com/assets/1351571/17832104/1c6d8e3e-66c9-11e6-83e2-85716cbb7a6c.png)

**Comment by sparerd** [comment]
Looks great - I'll talk with the rest of the team.

**Comment by sparerd** [comment]
@benwa Go ahead and submit the PR. In the coming weeks we will be considering a move of our current domain to these github pages
