### ISSUE TITLE
Some changes for the "Contribute" page

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG.github.io#10]
To keep things as simple as possible and prevent having the same information on multiple places - which makes it harder to maintain - the contribution information on should be removed and the tab should be simply called _Donate_

![image](https://user-images.githubusercontent.com/22905106/84575671-259ab780-adaf-11ea-8075-547847e7c12b.png)

**Comment by benwa** [comment]
I've wanted to explore using https://opencollective.com/ as there are many OSS projects using it which might help discoverability. Again, I'd like @sparerd's and @kmscode's opinion before removing information from a page.
