### ISSUE TITLE
Remove header tabs

### ISSUE THREAD

**Issue by farosch** [mRemoteNG/mRemoteNG.github.io#11]
Removing the two header tabs pointing to Github and also the "GitHub Twitter Reddit Gitter"-Footer but instead add two badges for reddit and gitter under the mremoteNG logo.
Ensures a clean and clear navigation.

![image](https://user-images.githubusercontent.com/22905106/84576250-81ffd600-adb3-11ea-9c46-76e8f09ae3ff.png)

**Comment by benwa** [comment]
The buttons are from third party libraries; I'm not sure if Reddit or Gitter have those-and I have no artistic ability ;)
We could use https://shields.io/ like in the main project's readme, though I'd like to hear @sparerd's and @kmscode's opinions on this in any case.

**Comment by farosch** [comment]
> The buttons are from third party libraries; I'm not sure if Reddit or Gitter have those-and I have no artistic ability ;)

Me neither unfortunately..

> We could use https://shields.io/ like in the main project's readme

That might be a good idea

**Comment by benwa** [comment]
I was looking at shields.io a bit yesterday and think I want to switch to it anyways so there's one domain to fetch from instead of two (twitter and github). I still would like to hear the opinions from the other guys about moving the other links to the jumbotron.

**Comment by farosch** [comment]
yeah, that's a good point. Keep cross loading as low as possible...

> I was looking at shields.io a bit yesterday and think I want to switch to it anyways so there's one domain to fetch from instead of two (twitter and github)

Abnsolutely - I hope I'll get ahold of them soon, espacially @sparerd :P

**Comment by Kvarkas** [comment]
I think we can close this as obsolete
