### ISSUE TITLE
website shows like it zoomed in from some update.

### ISSUE THREAD

**Issue by zapy85** [mRemoteNG/mRemoteNG.github.io#22]
![image](https://user-images.githubusercontent.com/3597565/174293899-c0ba1957-5e47-4443-b413-5bd1ba002c13.png)

**Comment by Kvarkas** [comment]
close as reported in wrong repository (reported in right repository so will be dealing with that issue at that place)

**Comment by Kvarkas** [comment]
closed by mistake so reopened

**Comment by Kvarkas** [comment]
has been fixed
