### ISSUE TITLE
Requested tweaks

### ISSUE THREAD

**Issue by kmscode** [mRemoteNG/mRemoteNG.github.io#3]
* Remove Quick Look Video (we didn't create that and it's based on a 3ish year old build, would like to avoid confusion even though it was attributed properly)
* Download page should have 2 links (or sections to links):
  * Latest/Stable (Final): https://github.com/mRemoteNG/mRemoteNG/releases/latest
     * This could link to zip/msi/source as in the past
  * Unstable/Alpha/Beat (Pre-release): https://github.com/mRemoteNG/mRemoteNG/releases
    * This can just link to the github releases page
* Remove Contribute v2 (I don't think we want to deal with CloudFlare or Stripe at this time - @sparerd ?)
* Documentation should link to https://github.com/mRemoteNG/mRemoteNG/wiki
* Footer github link should link to https://github.com/mRemoteNG/mRemoteNG
* Add Footer link to Gitter:  https://gitter.im/mRemoteNG/PublicChat
* Source should link to https://github.com/mRemoteNG/mRemoteNG
* Report a bug should link to https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug
* Remove forum link (not widely used, I think we should eventually decommission them - @sparerd ?)
* upper left mRemoteNG should link to https://github.com/mRemoteNG/mRemoteNG

**Comment by kmscode** [comment]
@benwa #2 accepted - FANTASTIC!!!!

Any chance you could take care of these things? Or give us a little direction to make sure we don't screw up your hard work? :wink:

**Comment by benwa** [comment]
Sure thing, I'll get on it and submit a PR asap.  Trying to fix git on my work computer at the moment.
The broken links were because I was hosting off of a `gh-pages` branch instead of an organization.  I'll fix those right up.

I'd consider using CloudFlare just to get https on the site even if you don't want to go with Stripe.

**Comment by kmscode** [comment]
No need for a PR. Invited you to a team that has write access to this repo! Thanks a bunch for the awesome work!!!
